import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Heade from "@/components/layout/heade";
import Indexlayout from "@/components/layout";
import "@/../public/css/bootstrap.min.css";
import "@/../public/css/slicknav.min.css";
import "@/../public/css/swiper-bundle.min.css";
import "@/../public/css/all.min.css";
import "@/../public/css/animate.css";
import "@/../public/css/magnific-popup.css";
import "@/../public/css/mousecursor.css";
import "@/../public/css/custom.css";
import Scripts from "@/components/layout/scripts";
import { DM_Sans,Sora } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "700"],
});


export const metadata: Metadata = {
  title: "Delta International Institute",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <Heade />
      <body
        className={`antialiased tt-transition tt-lightmode-on tt-noise tt-magic-cursor tt-smooth-scroll ${sora.className}`}
      >
        <Indexlayout>{children}</Indexlayout>
   
      <Scripts />
      </body>
    </html>
  );
}
